/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSlotsRouteImport } from './routes/_app.slots'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppGuardRouteImport } from './routes/_app.guard'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAiInsightsRouteImport } from './routes/_app.ai-insights'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppSlotsSectionRouteImport } from './routes/_app.slots_.$section'
import { Route as AppSettingsSectionRouteImport } from './routes/_app.settings_.$section'
import { Route as AppGuardSectionRouteImport } from './routes/_app.guard_.$section'
import { Route as AppDashboardSectionRouteImport } from './routes/_app.dashboard_.$section'
import { Route as AppAiInsightsSectionRouteImport } from './routes/_app.ai-insights_.$section'
import { Route as AppAdminSectionRouteImport } from './routes/_app.admin_.$section'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlotsRoute = AppSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardRoute = AppGuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSlotsSectionRoute = AppSlotsSectionRouteImport.update({
  id: '/slots_/$section',
  path: '/slots/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/settings_/$section',
  path: '/settings/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardSectionRoute = AppGuardSectionRouteImport.update({
  id: '/guard_/$section',
  path: '/guard/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardSectionRoute = AppDashboardSectionRouteImport.update({
  id: '/dashboard_/$section',
  path: '/dashboard/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsSectionRoute = AppAiInsightsSectionRouteImport.update({
  id: '/ai-insights_/$section',
  path: '/ai-insights/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSectionRoute = AppAdminSectionRouteImport.update({
  id: '/admin_/$section',
  path: '/admin/$section',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/dashboard': typeof AppDashboardRoute
  '/guard': typeof AppGuardRoute
  '/settings': typeof AppSettingsRoute
  '/slots': typeof AppSlotsRoute
  '/admin/$section': typeof AppAdminSectionRoute
  '/ai-insights/$section': typeof AppAiInsightsSectionRoute
  '/dashboard/$section': typeof AppDashboardSectionRoute
  '/guard/$section': typeof AppGuardSectionRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/slots/$section': typeof AppSlotsSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/dashboard': typeof AppDashboardRoute
  '/guard': typeof AppGuardRoute
  '/settings': typeof AppSettingsRoute
  '/slots': typeof AppSlotsRoute
  '/admin/$section': typeof AppAdminSectionRoute
  '/ai-insights/$section': typeof AppAiInsightsSectionRoute
  '/dashboard/$section': typeof AppDashboardSectionRoute
  '/guard/$section': typeof AppGuardSectionRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/slots/$section': typeof AppSlotsSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai-insights': typeof AppAiInsightsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/guard': typeof AppGuardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/slots': typeof AppSlotsRoute
  '/_app/admin_/$section': typeof AppAdminSectionRoute
  '/_app/ai-insights_/$section': typeof AppAiInsightsSectionRoute
  '/_app/dashboard_/$section': typeof AppDashboardSectionRoute
  '/_app/guard_/$section': typeof AppGuardSectionRoute
  '/_app/settings_/$section': typeof AppSettingsSectionRoute
  '/_app/slots_/$section': typeof AppSlotsSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-insights'
    | '/dashboard'
    | '/guard'
    | '/settings'
    | '/slots'
    | '/admin/$section'
    | '/ai-insights/$section'
    | '/dashboard/$section'
    | '/guard/$section'
    | '/settings/$section'
    | '/slots/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-insights'
    | '/dashboard'
    | '/guard'
    | '/settings'
    | '/slots'
    | '/admin/$section'
    | '/ai-insights/$section'
    | '/dashboard/$section'
    | '/guard/$section'
    | '/settings/$section'
    | '/slots/$section'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/ai-insights'
    | '/_app/dashboard'
    | '/_app/guard'
    | '/_app/settings'
    | '/_app/slots'
    | '/_app/admin_/$section'
    | '/_app/ai-insights_/$section'
    | '/_app/dashboard_/$section'
    | '/_app/guard_/$section'
    | '/_app/settings_/$section'
    | '/_app/slots_/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/slots': {
      id: '/_app/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof AppSlotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard': {
      id: '/_app/guard'
      path: '/guard'
      fullPath: '/guard'
      preLoaderRoute: typeof AppGuardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-insights': {
      id: '/_app/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/slots_/$section': {
      id: '/_app/slots_/$section'
      path: '/slots/$section'
      fullPath: '/slots/$section'
      preLoaderRoute: typeof AppSlotsSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/$section': {
      id: '/_app/settings_/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard_/$section': {
      id: '/_app/guard_/$section'
      path: '/guard/$section'
      fullPath: '/guard/$section'
      preLoaderRoute: typeof AppGuardSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/$section': {
      id: '/_app/dashboard_/$section'
      path: '/dashboard/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof AppDashboardSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-insights_/$section': {
      id: '/_app/ai-insights_/$section'
      path: '/ai-insights/$section'
      fullPath: '/ai-insights/$section'
      preLoaderRoute: typeof AppAiInsightsSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin_/$section': {
      id: '/_app/admin_/$section'
      path: '/admin/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AppAdminSectionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGuardRoute: typeof AppGuardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSlotsRoute: typeof AppSlotsRoute
  AppAdminSectionRoute: typeof AppAdminSectionRoute
  AppAiInsightsSectionRoute: typeof AppAiInsightsSectionRoute
  AppDashboardSectionRoute: typeof AppDashboardSectionRoute
  AppGuardSectionRoute: typeof AppGuardSectionRoute
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppSlotsSectionRoute: typeof AppSlotsSectionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGuardRoute: AppGuardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSlotsRoute: AppSlotsRoute,
  AppAdminSectionRoute: AppAdminSectionRoute,
  AppAiInsightsSectionRoute: AppAiInsightsSectionRoute,
  AppDashboardSectionRoute: AppDashboardSectionRoute,
  AppGuardSectionRoute: AppGuardSectionRoute,
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppSlotsSectionRoute: AppSlotsSectionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
