/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVisitorsRouteImport } from './routes/_app.visitors'
import { Route as AppSlotsRouteImport } from './routes/_app.slots'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppGuardRouteImport } from './routes/_app.guard'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAiInsightsRouteImport } from './routes/_app.ai-insights'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisitorsRoute = AppVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AppRoute,
} as any)
const AppSlotsRoute = AppSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardRoute = AppGuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/dashboard': typeof AppDashboardRoute
  '/guard': typeof AppGuardRoute
  '/settings': typeof AppSettingsRoute
  '/slots': typeof AppSlotsRoute
  '/visitors': typeof AppVisitorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/dashboard': typeof AppDashboardRoute
  '/guard': typeof AppGuardRoute
  '/settings': typeof AppSettingsRoute
  '/slots': typeof AppSlotsRoute
  '/visitors': typeof AppVisitorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai-insights': typeof AppAiInsightsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/guard': typeof AppGuardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/slots': typeof AppSlotsRoute
  '/_app/visitors': typeof AppVisitorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-insights'
    | '/dashboard'
    | '/guard'
    | '/settings'
    | '/slots'
    | '/visitors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-insights'
    | '/dashboard'
    | '/guard'
    | '/settings'
    | '/slots'
    | '/visitors'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/ai-insights'
    | '/_app/dashboard'
    | '/_app/guard'
    | '/_app/settings'
    | '/_app/slots'
    | '/_app/visitors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/visitors': {
      id: '/_app/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AppVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/slots': {
      id: '/_app/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof AppSlotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard': {
      id: '/_app/guard'
      path: '/guard'
      fullPath: '/guard'
      preLoaderRoute: typeof AppGuardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-insights': {
      id: '/_app/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGuardRoute: typeof AppGuardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSlotsRoute: typeof AppSlotsRoute
  AppVisitorsRoute: typeof AppVisitorsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGuardRoute: AppGuardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSlotsRoute: AppSlotsRoute,
  AppVisitorsRoute: AppVisitorsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
